// views/svelte/src/components/Message.svelte
<script lang="ts">
    import { MessageType } from '../enums';
    import ErrorIcon from './icons/ErrorIcon.svelte';
    import InfoIcon from './icons/InfoIcon.svelte';
    import SuccessIcon from './icons/SuccessIcon.svelte';
    import WarningIcon from './icons/WarningIcon.svelte';

    export let type: MessageType;
    export let content: string;
</script>

<div
    class="flex flex-row items-center gap-[8px] text-white text-base select-none fade-in"
    class:py-[4px]={type !== MessageType.Default && type !== MessageType.Empty}
    class:px-[8px]={type !== MessageType.Empty}
    class:info={type === MessageType.Info}
    class:success={type === MessageType.Success}
    class:warning={type === MessageType.Warning}
    class:error={type === MessageType.Error}
>
    {#if type === MessageType.Info}
        <InfoIcon />
    {:else if type === MessageType.Success}
        <SuccessIcon />
    {:else if type === MessageType.Warning}
        <WarningIcon />
    {:else if type === MessageType.Error}
        <ErrorIcon />
    {/if}
    <div>
        {@html content}
    </div>
</div>

<style lang="scss">
    @import 'Message.scss';
</style>

// views/react/src/components/Message.tsx
import { MessageType } from '../enums';
import { InfoIcon } from './icons/InfoIcon';
import { SuccessIcon } from './icons/SuccessIcon';
import { WarningIcon } from './icons/WarningIcon';
import { ErrorIcon } from './icons/ErrorIcon';
import classnames from 'classnames';
import './Message.scss';

export function Message(props: { type: MessageType; content: string }) {
    return (
        <div
            className={classnames('flex flex-row items-center gap-[8px] text-white text-base select-none fade-in', {
                'py-[4px]': props.type !== MessageType.Default && props.type !== MessageType.Empty,
                'px-[8px]': props.type !== MessageType.Empty,
                info: props.type === MessageType.Info,
                success: props.type === MessageType.Success,
                warning: props.type === MessageType.Warning,
                error: props.type === MessageType.Error,
            })}
        >
            {props.type === MessageType.Info && <InfoIcon />}
            {props.type === MessageType.Success && <SuccessIcon />}
            {props.type === MessageType.Warning && <WarningIcon />}
            {props.type === MessageType.Error && <ErrorIcon />}
            <div dangerouslySetInnerHTML={{ __html: props.content }} />
        </div>
    );
}
