// views/vue/src/components/CommandSuggestions.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import type { CommandSuggestion, MatchedCommand } from '../interfaces';
import { useChatStore } from '../stores';
import commandsJson from '../commands.json';

// --------------------------------------------------------------
// Chat Store
// --------------------------------------------------------------

const { focus, message, setMessage, options } = useChatStore();

// --------------------------------------------------------------
// Local Variables
// --------------------------------------------------------------

const commands = ref(commandsJson as Array<CommandSuggestion>);
const matchedCommands = ref([] as Array<MatchedCommand>);
const selected = ref(-1);

// --------------------------------------------------------------
// Functions
// --------------------------------------------------------------

// Command suggestion selection ---------------------------------

/**
 * Selects the command suggestion depending on the key pressed.
 * @param event The keyboard event.
 */
function selectCommand(event: KeyboardEvent) {
    if (event.key !== 'ArrowDown' && event.key !== 'ArrowUp' && event.key !== 'Tab') return;
    if (matchedCommands.value.length === 0) return;

    if (event.key === 'ArrowUp' && matchedCommands.value.length > 1) selected.value = Math.max(0, selected.value - 1);
    else if (event.key === 'ArrowDown' && matchedCommands.value.length > 1)
        selected.value = Math.min(matchedCommands.value.length - 1, selected.value + 1);
    else if (event.key === 'Tab' && selected.value >= 0 && !(matchedCommands.value[selected.value].currentParam > -1))
        setMessage(matchedCommands.value[selected.value].name);

    event.preventDefault();
}

/**
 * Matches the current message against the available command suggestions.
 * @param message The message to match against.
 */
function updateMatchedCommands(message: string, commands: Array<CommandSuggestion>) {
    if (!message) {
        matchedCommands.value = [];
        return;
    }

    const words = message.split(' ');
    if (!words[0].startsWith(options.prefix)) {
        matchedCommands.value = [];
        return;
    }

    matchedCommands.value = commands
        .filter((command) => {
            const cmdName = words[0].startsWith(options.prefix) ? words[0].substring(1) : words[0];

            return (
                cmdName.length > 0 &&
                command.name.startsWith(cmdName) &&
                words.length - 1 <= (command.params?.length ?? 0)
            );
        })
        .splice(0, options.maxCommandSuggestions)
        .map((command) => {
            let currentParam = -1;
            const cmdName = options.prefix + command.name;

            if (words.length === 1 && words[0] === cmdName) currentParam = 0;
            if (words.length > 1 && words.length - 1 <= (command?.params?.length ?? 0)) currentParam = words.length - 1;
            return { currentParam, ...command, name: cmdName };
        });
    matchedCommands.value.length === 0 ? (selected.value = -1) : (selected.value = 0);
}

// Adding the command suggestion --------------------------------

/**
 * Adds the command suggestion sent by the server.
 * @param suggestion The command suggestion to add.
 */
function addSuggestion(suggestion: CommandSuggestion | Array<CommandSuggestion>) {
    Array.isArray(suggestion)
        ? (commands.value = [...commands.value, ...suggestion])
        : (commands.value = [...commands.value, suggestion]);
}

/**
 * Removes all command suggestions.
 */
function removeSuggestions() {
    commands.value = [];
}

// --------------------------------------------------------------
// Hooks
// --------------------------------------------------------------

// Effects ------------------------------------------------------

// Listens for message changes and updates the matched commands.
watch([message, commands], ([message, commands]) => updateMatchedCommands(message, commands));

// Mount --------------------------------------------------------

onMounted(() => {
    window.addEventListener('keydown', selectCommand);
    window?.alt?.on('vchat:addSuggestion', addSuggestion);
    window?.alt?.on('vchat:removeSuggestions', removeSuggestions);
});

// Unmount ------------------------------------------------------

onUnmounted(() => {
    window.removeEventListener('keydown', selectCommand);
    window?.alt?.off('vchat:addSuggestion', addSuggestion);
    window?.alt?.off('vchat:removeSuggestions', removeSuggestions);
});
</script>

<template>
    <div
        class="mt-[4px] text-white flex flex-col transition origin-top scale-y-0"
        :class="{
            'scale-y-0': !focus || matchedCommands.length === 0,
            'scale-y-100': focus && matchedCommands.length > 0,
        }"
    >
        <div
            v-for="(matchedCommand, cmdIndex) in matchedCommands"
            class="bg-black px-[16px] py-[8px] transition duration-200 select-none"
            :class="{
                'bg-opacity-50': cmdIndex === selected,
                'bg-opacity-30': cmdIndex !== selected,
                'hover:bg-opacity-50': cmdIndex !== selected,
            }"
        >
            <div class="flex text-base text-white text-opacity-100">
                <span :class="{ 'font-bold': matchedCommand.currentParam === 0 }">{{ matchedCommand.name }}</span>
                <span
                    v-for="(param, paramIndex) in matchedCommand.params"
                    class="ml-1"
                    :class="{ 'font-bold': matchedCommand.currentParam === paramIndex + 1 }"
                >
                    [{{ param.name }}]
                </span>
            </div>
            <div class="text-xs text-white text-opacity-50">
                {{
                    (matchedCommand.currentParam <= 0
                        ? matchedCommand.description
                        : matchedCommand.params![matchedCommand.currentParam - 1].description) ?? ''
                }}
            </div>
        </div>
    </div>
</template>

// views/svelte/src/components/CommandSuggestions.svelte
<script lang="ts">
    import type { CommandSuggestion, MatchedCommand } from '../interfaces';
    import { onDestroy, onMount } from 'svelte';
    import { useChatStore } from '../stores';
    import commandsJson from '../commands.json';

    // --------------------------------------------------------------
    // Chat Store
    // --------------------------------------------------------------

    const { focus, message, setMessage, options } = useChatStore();

    // --------------------------------------------------------------
    // Local Variables
    // --------------------------------------------------------------

    let commands: Array<CommandSuggestion> = commandsJson;
    let matchedCommands: Array<MatchedCommand> = [];
    let selected: number = -1;

    // --------------------------------------------------------------
    // Functions
    // --------------------------------------------------------------

    // Command suggestion selection ---------------------------------

    /**
     * Selects the command suggestion depending on the key pressed.
     * @param event The keyboard event.
     */
    function selectCommand(event: KeyboardEvent) {
        if (event.key !== 'ArrowDown' && event.key !== 'ArrowUp' && event.key !== 'Tab') return;
        if (matchedCommands.length === 0) return;

        if (event.key === 'ArrowUp' && matchedCommands.length > 1) selected = Math.max(0, selected - 1);
        else if (event.key === 'ArrowDown' && matchedCommands.length > 1)
            selected = Math.min(matchedCommands.length - 1, selected + 1);
        else if (event.key === 'Tab' && selected >= 0 && !(matchedCommands[selected].currentParam > -1))
            setMessage(matchedCommands[selected].name);

        event.preventDefault();
    }

    /**
     * Matches the current message against the available command suggestions.
     * @param message The message to match against.
     */
    function updateMatchedCommands(message: string, commands: Array<CommandSuggestion>) {
        if (!message) {
            matchedCommands = [];
            return;
        }

        const words = message.split(' ');
        if (!words[0].startsWith($options.prefix)) {
            matchedCommands = [];
            return;
        }

        matchedCommands = commands
            .filter((command) => {
                const cmdName = words[0].startsWith($options.prefix) ? words[0].substring(1) : words[0];

                return (
                    cmdName.length > 0 &&
                    command.name.startsWith(cmdName) &&
                    words.length - 1 <= (command.params?.length ?? 0)
                );
            })
            .splice(0, $options.maxCommandSuggestions)
            .map((command) => {
                let currentParam = -1;
                const cmdName = $options.prefix + command.name;

                if (words.length === 1 && words[0] === cmdName) currentParam = 0;
                if (words.length > 1 && words.length - 1 <= (command.params.length ?? 0))
                    currentParam = words.length - 1;

                return { currentParam, ...command, name: cmdName };
            });
        matchedCommands.length === 0 ? (selected = -1) : (selected = 0);
    }

    // Adding the command suggestion --------------------------------

    /**
     * Adds the command suggestion sent by the server.
     * @param suggestion The command suggestion to add.
     */
    function addSuggestion(suggestion: CommandSuggestion | Array<CommandSuggestion>) {
        Array.isArray(suggestion) ? (commands = [...commands, ...suggestion]) : (commands = [...commands, suggestion]);
    }

    /**
     * Removes all command suggestions.
     */
    function removeSuggestions() {
        commands = [];
    }

    // --------------------------------------------------------------
    // Hooks
    // --------------------------------------------------------------

    // Effects ------------------------------------------------------

    // Listens for message changes and updates the matched commands.
    $: updateMatchedCommands($message, commands);
    const unsubOptions = options.subscribe(() => updateMatchedCommands($message, commands));

    // Mount --------------------------------------------------------

    onMount(() => {
        window?.alt?.on('vchat:addSuggestion', addSuggestion);
        window?.alt?.on('vchat:removeSuggestions', removeSuggestions);
    });

    // Unmount ------------------------------------------------------

    onDestroy(() => {
        unsubOptions();

        window?.alt?.off('vchat:addSuggestion', addSuggestion);
        window?.alt?.off('vchat:removeSuggestions', removeSuggestions);
    });
</script>

<div
    class="mt-[4px] text-white flex flex-col transition origin-top scale-y-0"
    class:!scale-y-100={matchedCommands.length > 0 && focus}
>
    {#each matchedCommands as matchedCommand, cmdIndex}
        <div
            class="bg-black px-[16px] py-[8px] transition duration-200 select-none"
            class:bg-opacity-50={cmdIndex === selected}
            class:bg-opacity-30={cmdIndex !== selected}
            class:hover:bg-opacity-50={cmdIndex !== selected}
        >
            <div class="flex text-base text-white text-opacity-100">
                <span class:font-bold={matchedCommand.currentParam === 0}>
                    {matchedCommand.name}
                </span>
                {#each matchedCommand.params ?? [] as param, paramIndex}
                    <span class="ml-1" class:font-bold={matchedCommand.currentParam === paramIndex + 1}>
                        [{param.name}]
                    </span>
                {/each}
            </div>
            <div class="text-xs text-white text-opacity-50">
                {(matchedCommand.currentParam <= 0
                    ? matchedCommand.description
                    : matchedCommand.params[matchedCommand.currentParam - 1].description) ?? ''}
            </div>
        </div>
    {/each}
</div>

<svelte:window on:keydown={selectCommand} />
